version: "3.8"

services:
    server:
        build:
            context: .
            target: base_server
        container_name: minecraft-server
        ports:
            - "25565:25565"
        environment:
            - RAM=1G
                   